01 Sign-in page
aleksandr24789/yum-plan pull request #1
Opened 2024-03-31 12:33 UTC by aleksandr24789

Add Sign-in page with GitHub provider

2024-03-31 17:02 UTC, andrey-kudinov requested changes

2024-03-31 17:02 UTC, andrey-kudinov commented on src/components/FormButton/FormButton.js
> +    <button
я противник таких маленьких компонентов. тут всего лишь один тег без логики, но ты оборачиваешь его react+ts

компонент для той же кнопки мог бы иметь место если она сложная - внутри опционально крутится лоадер, разные стили на разных кнопок, кнопка может быть ссылкой и тп

2024-03-31 17:02 UTC, andrey-kudinov commented on src/pages/signin/index.js
> +          <h1 className={styles['signin-title']}>Войти с помощью</h1>
я думаю h1 мог бы быть Авторизация или Регистрация и быть sr-only, а здесь h2

2024-04-01 05:47 UTC, aleksandr24789 commented on src/components/FormButton/FormButton.css
> +.form-button {
Исправлено: компонент удален, пока в нем нет необходимости

2024-04-01 05:47 UTC, aleksandr24789 commented on src/pages/signin/index.js
> +          <h1 className={styles['signin-title']}>Войти с помощью</h1>
Исправлено на h2

2024-04-01 06:10 UTC, merged