03 user settings page
aleksandr24789/yum-plan pull request #3
Opened 2024-04-25 07:42 UTC by aleksandr24789

Создана страница изменения данных пользователя в БД - пока отрабатывается на имени (работает).

Остановился здесь: попытка создать стейт в контексте, в который записать данные пользователя из БД, а потом брать в хедере и на странице изменения настроек. Так как после хотя бы одного изменения, данные пользователя из сессии провайдера больше не совпадают с данными в БД, т.е. БД должна быть источником данных в стейт.

Текущий код в этом провайдере неактуальный. В поисках как правильно получить запись нужного пользователя. В /api/changeuser изменения в БД вносятся по уникальному id пользователя, который берется на серверной стороне через getToken(), и как я понял документацию не рекомендуется его передавать клиенту без необходимости. Провайдер стейта работает на клиенте (из руководства), и при инициализации надо получить из БД запись, и потом ещё и обновлять. Если не критично, то через useEffect() буду получать (асин[ронный запрос в prisma)?

2024-04-25 07:44 UTC, aleksandr24789 commented on src/providers/stateContext.js
Остановился здесь: попытка создать стейт в контексте, в который записать данные пользователя из БД, а потом брать в хедере и на странице изменения настроек. Так как после хотя бы одного изменения, данные пользователя из сессии провайдера больше не совпадают с данными в БД, т.е. БД должна быть источником данных в стейт.

Текущий код в этом провайдере неактуальный. В поисках как правильно получить запись нужного пользователя. В /api/changeuser изменения в БД вносятся по уникальному id пользователя, который берется на серверной стороне через getToken(), и как я понял документацию не рекомендуется его передавать клиенту без необходимости. Провайдер стейта работает на клиенте (из руководства), и при инициализации надо получить из БД запись, и потом ещё и обновлять. Если не критично, то через useEffect() буду получать (асин[ронный запрос в prisma)?

2024-05-01 07:24 UTC, aleksandr24789 commented
![2024-05-01 12-20-43 localhost](https://github.com/aleksandr24789/yum-plan/assets/87819638/16ad06c8-0c28-4bc2-be78-4b5d47e49bfc)
![2024-05-01 12-21-43 Visual Studio Code](https://github.com/aleksandr24789/yum-plan/assets/87819638/19ccfc94-3e90-4465-acd8-54bd67925cdc)

2024-05-04 14:01 UTC, andrey-kudinov requested changes

2024-05-04 14:01 UTC, andrey-kudinov commented on src/components/SetUserForm/SetUserForm.module.css
> +  width: 25rem;
Я бы советовал в Рем только шрифтовые моменты, а остальное в пикселях

Иначе теряется преимущество ремов и не понятно зачем их использовать

2024-05-04 14:01 UTC, andrey-kudinov commented on src/components/SetUserForm/SetUserForm.module.css
> +.avatar-input:focus {
Лучше focus-visible

2024-05-04 14:01 UTC, andrey-kudinov commented on src/components/UserAvatar/UserAvatar.js
> +          alt="Аватар"
Иногда на рус, иногда на англ пишешь

2024-05-07 07:51 UTC, merged